name: Build release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Generate POT
        uses: hivepress/action-generate-pot@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          composer install -o --no-dev
          if [ -f package.json ]; then npm install --omit=dev && node build.js; fi

      - name: Pack release
        run: |
          rm -rf .git* composer.* phpcs.xml package.json package-lock.json build.js node_modules README.md
          cd ..
          zip -r ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}

      - name: Upload release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ../${{ github.event.repository.name }}.zip
